name = "ra4m1_hal"
description = ""
version = "0.1.0-dev"

authors = ["Marcus Gigandet"]
maintainers = ["Marcus Gigandet <78104059+marcusgigandet@users.noreply.github.com>"]
licenses = "LGPL-3.0-or-later"
website = "https://github.com/marcusgigandet/ra4m1_hal"
tags = []

[[actions]]
type = "pre-build"
command = [
    "python3",
    "-m",
    "vendor.toolbox.scripts.copyright",
    "--config",
    "config.toml",
    "--directory",
    ".",
]

[[depends-on]]
cortex_m = "^1"
gnat_arm_elf = ">=16.1"

[configuration.values]
cortex_m.core = "m4"
